organization = "118518422342"
project="secops-project-348011"
demo_project="solution-demos-332013"
region="us-central1"
iap_user="pensande@agarsand.altostrat.com"
create_dev_gke_cluster = false
create_iap_run_sql_demo = false
create_ids_demo = false
create_cc_demo = true
primus_project = "primus-bank-421307"
secundus_project = "secundus-bank-421307"
recaptcha_site_key = "6LcGeukhAAAAAAfjGfl0YIEtMEoUIy2uq_QjhJBQ"